subprojects {
    apply plugin: 'java-library'

    group = mod_group_id
    version = mod_version

    java.toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)

    repositories {
        mavenCentral()
        maven { url = 'https://maven.neoforged.net/releases' }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}